 ## Data Mining and Machine Learning
 ## Feature Engineering: Feature Discretization(Binning)
 ### Edgar Acuna
 ####  Febrero 2020

In [46]:
import pandas as pd
import numpy as np
from sklearn import preprocessing 
from sklearn.preprocessing import KBinsDiscretizer
import Orange

In [47]:
pd.__version__

'0.24.2'

In [48]:
#Leyendo el dataset wine de la UCI
#wine_data=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv", sep=";")
wine_data=pd.read_csv("https://academic.uprm.edu/eacuna/winequality-red.csv", sep=";")
wine_data.head(5)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [49]:
wine_data.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1599.000000       1599.000000  1599.000000     1599.000000   
mean        8.319637          0.527821     0.270976        2.538806   
std         1.741096          0.179060     0.194801        1.409928   
min         4.600000          0.120000     0.000000        0.900000   
25%         7.100000          0.390000     0.090000        1.900000   
50%         7.900000          0.520000     0.260000        2.200000   
75%         9.200000          0.640000     0.420000        2.600000   
max        15.900000          1.580000     1.000000       15.500000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1599.000000          1599.000000           1599.000000  1599.000000   
mean      0.087467            15.874922             46.467792     0.996747   
std       0.047065            10.460157             32.895324     0.001887   
min       0.012000             1.000000              6.000000     0.990070   
25%       0.070000             7.000000             22.000000     0.995600   
50%       0.079000            14.000000             38.000000     0.996750   
75%       0.090000            21.000000             62.000000     0.997835   
max       0.611000            72.000000            289.000000     1.003690   

                pH    sulphates      alcohol      quality  
count  1599.000000  1599.000000  1599.000000  1599.000000  
mean      3.311113     0.658149    10.422983     5.636023  
std       0.154386     0.169507     1.065668     0.807569  
min       2.740000     0.330000     8.400000     3.000000  
25%       3.210000     0.550000     9.500000     5.000000  
50%       3.310000     0.620000    10.200000     6.000000  
75%       3.400000     0.730000    11.100000     6.000000  
max       4.010000     2.000000    14.900000     8.000000

In [50]:
df=wine_data.copy()

## 1. Equal-width Discretization  using Pandas

In [51]:
#Binning columm pH using 4 bins 
wine_data['pH_ex1'] = pd.cut(wine_data['pH'], bins=4,precision=2)
wine_data['pH_ex1'].value_counts()

(3.06, 3.38]    1007
(3.38, 3.69]     503
(2.74, 3.06]      72
(3.69, 4.01]      17
Name: pH_ex1, dtype: int64

#### Eliminating the last column(classes)

In [52]:
dfa=df.drop('quality',axis=1)

#### Binning all columns

In [53]:
dfdisc= dfa.apply(lambda x: pd.cut(x,4,precision=2), axis=0)
dfdisc.head()

fixed acidity volatile acidity     citric acid residual sugar  \
0    (4.59, 7.42]     (0.48, 0.85]  (-0.001, 0.25]   (0.89, 4.55]   
1   (7.42, 10.25]     (0.85, 1.21]  (-0.001, 0.25]   (0.89, 4.55]   
2   (7.42, 10.25]     (0.48, 0.85]  (-0.001, 0.25]   (0.89, 4.55]   
3  (10.25, 13.08]     (0.12, 0.48]     (0.5, 0.75]   (0.89, 4.55]   
4    (4.59, 7.42]     (0.48, 0.85]  (-0.001, 0.25]   (0.89, 4.55]   

       chlorides free sulfur dioxide total sulfur dioxide         density  \
0  (0.011, 0.16]       (0.93, 18.75]        (5.72, 76.75]    (0.997, 1.0]   
1  (0.011, 0.16]       (18.75, 36.5]        (5.72, 76.75]  (0.993, 0.997]   
2  (0.011, 0.16]       (0.93, 18.75]        (5.72, 76.75]    (0.997, 1.0]   
3  (0.011, 0.16]       (0.93, 18.75]        (5.72, 76.75]    (0.997, 1.0]   
4  (0.011, 0.16]       (0.93, 18.75]        (5.72, 76.75]    (0.997, 1.0]   

             pH     sulphates        alcohol  
0  (3.38, 3.69]  (0.33, 0.75]  (8.39, 10.02]  
1  (3.06, 3.38]  (0.33, 0.75]  (8.39, 10.02]  
2  (3.06, 3.38]  (0.33, 0.75]  (8.39, 10.02]  
3  (3.06, 3.38]  (0.33, 0.75]  (8.39, 10.02]  
4  (3.38, 3.69]  (0.33, 0.75]  (8.39, 10.02]

In [54]:
dfd2sc= dfa.apply(lambda x: pd.cut(x,4,precision=2,labels=False), axis=0)
dfd2sc.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0              0                 1            0               0          0   
1              1                 2            0               0          0   
2              1                 1            0               0          0   
3              2                 0            2               0          0   
4              0                 1            0               0          0   

   free sulfur dioxide  total sulfur dioxide  density  pH  sulphates  alcohol  
0                    0                     0        2   2          0        0  
1                    1                     0        1   1          0        0  
2                    0                     0        2   1          0        0  
3                    0                     0        2   1          0        0  
4                    0                     0        2   2          0        0

###  2. Equal-width Discretization using KBinsDiscretizer from Scikit-learn

#### Binning  one column of the data in 10 values using equal width bins

In [55]:
est = KBinsDiscretizer(n_bins=10, encode='ordinal', strategy='uniform')
df1=np.array(df['pH']).reshape(-1,1)
est.fit(df1)

Xt = est.transform(df1)
print(Xt)  

[[6.]
 [3.]
 [4.]
 ...
 [5.]
 [6.]
 [5.]]


In [56]:
#Converting the array into dataframe
tempodf=pd.DataFrame(Xt)
tempodf.columns=["pH_disc"]
tempodf.head()

pH_disc
0      6.0
1      3.0
2      4.0
3      3.0
4      6.0

### Bining all the columns

In [57]:
est.fit(dfa)

Xt1 = est.transform(dfa)
print(Xt1)  

[[2. 3. 0. ... 6. 1. 1.]
 [2. 5. 0. ... 3. 2. 2.]
 [2. 4. 0. ... 4. 1. 2.]
 ...
 [1. 2. 1. ... 5. 2. 4.]
 [1. 3. 1. ... 6. 2. 2.]
 [1. 1. 4. ... 5. 1. 4.]]


### 3. Equal  width Discretization using my own program

In [58]:
wine_data.columns.tolist()

['fixed acidity',
 'volatile acidity',
 'citric acid',
 'residual sugar',
 'chlorides',
 'free sulfur dioxide',
 'total sulfur dioxide',
 'density',
 'pH',
 'sulphates',
 'alcohol',
 'quality',
 'pH_ex1']

In [59]:
#Discretization by equal width\
#The output can be an either integer or an interval 
def disc_col_ew(df,str,k,out):
    df1=df[str]
    bins=np.linspace(df1.min(), df1.max(),k)
    if out=="num":
        df1=pd.cut(df1,bins=bins,include_lowest=True, right=True,labels=False)
    else:
        bins[0]=float('-inf')
        bins[k-1]=float('inf')
        df1=pd.cut(df1,bins=bins,include_lowest=True, right=True)  
    return df1

In [60]:
disc_col_ew(dfa,'pH',10,out="symb")

0       (3.446, 3.587]
1       (3.163, 3.304]
2       (3.163, 3.304]
3       (3.022, 3.163]
4       (3.446, 3.587]
5       (3.446, 3.587]
6       (3.163, 3.304]
7       (3.304, 3.446]
8       (3.304, 3.446]
9       (3.304, 3.446]
10      (3.163, 3.304]
11      (3.304, 3.446]
12      (3.446, 3.587]
13      (3.163, 3.304]
14      (3.022, 3.163]
15      (3.163, 3.304]
16      (3.163, 3.304]
17      (3.022, 3.163]
18      (3.304, 3.446]
19      (3.022, 3.163]
20      (3.304, 3.446]
21      (3.446, 3.587]
22      (3.163, 3.304]
23      (3.163, 3.304]
24      (3.304, 3.446]
25      (3.304, 3.446]
26      (3.163, 3.304]
27      (3.163, 3.304]
28      (3.446, 3.587]
29      (3.304, 3.446]
             ...      
1569    (3.446, 3.587]
1570    (3.304, 3.446]
1571    (3.304, 3.446]
1572    (3.304, 3.446]
1573    (3.446, 3.587]
1574    (3.304, 3.446]
1575    (3.163, 3.304]
1576    (3.163, 3.304]
1577    (3.446, 3.587]
1578    (3.304, 3.446]
1579    (3.446, 3.587]
1580    (3.304, 3.446]
1581    (3.

In [61]:
def disc_ew(df,k,out):
    import numpy as np
    name=df.columns.tolist()
    disc=pd.DataFrame()
    for name in df.columns.tolist():
        disc[name]=disc_col_ew(df,name,k,out)
    return disc  

In [62]:
disc_ew(dfa,k=10,out="symb")

fixed acidity volatile acidity     citric acid  residual sugar  \
0       (7.111, 8.367]   (0.607, 0.769]   (-inf, 0.111]   (-inf, 2.522]   
1       (7.111, 8.367]   (0.769, 0.931]   (-inf, 0.111]  (2.522, 4.144]   
2       (7.111, 8.367]   (0.607, 0.769]   (-inf, 0.111]   (-inf, 2.522]   
3     (10.878, 12.133]    (-inf, 0.282]  (0.556, 0.667]   (-inf, 2.522]   
4       (7.111, 8.367]   (0.607, 0.769]   (-inf, 0.111]   (-inf, 2.522]   
5       (7.111, 8.367]   (0.607, 0.769]   (-inf, 0.111]   (-inf, 2.522]   
6       (7.111, 8.367]   (0.444, 0.607]   (-inf, 0.111]   (-inf, 2.522]   
7       (7.111, 8.367]   (0.607, 0.769]   (-inf, 0.111]   (-inf, 2.522]   
8       (7.111, 8.367]   (0.444, 0.607]   (-inf, 0.111]   (-inf, 2.522]   
9       (7.111, 8.367]   (0.444, 0.607]  (0.333, 0.444]  (5.767, 7.389]   
10      (5.856, 7.111]   (0.444, 0.607]   (-inf, 0.111]   (-inf, 2.522]   
11      (7.111, 8.367]   (0.444, 0.607]  (0.333, 0.444]  (5.767, 7.389]   
12       (-inf, 5.856]   (0.607, 0.769]   (-inf, 0.111]   (-inf, 2.522]   
13      (7.111, 8.367]   (0.607, 0.769]  (0.222, 0.333]   (-inf, 2.522]   
14      (8.367, 9.622]   (0.607, 0.769]  (0.111, 0.222]  (2.522, 4.144]   
15      (8.367, 9.622]   (0.607, 0.769]  (0.111, 0.222]  (2.522, 4.144]   
16      (8.367, 9.622]    (-inf, 0.282]  (0.556, 0.667]   (-inf, 2.522]   
17      (7.111, 8.367]   (0.444, 0.607]  (0.222, 0.333]   (-inf, 2.522]   
18      (7.111, 8.367]   (0.444, 0.607]   (-inf, 0.111]  (4.144, 5.767]   
19      (7.111, 8.367]   (0.282, 0.444]  (0.444, 0.556]   (-inf, 2.522]   
20      (8.367, 9.622]    (-inf, 0.282]  (0.444, 0.556]   (-inf, 2.522]   
21      (7.111, 8.367]   (0.282, 0.444]  (0.222, 0.333]   (-inf, 2.522]   
22      (7.111, 8.367]   (0.282, 0.444]  (0.111, 0.222]   (-inf, 2.522]   
23      (8.367, 9.622]   (0.444, 0.607]   (-inf, 0.111]   (-inf, 2.522]   
24      (5.856, 7.111]   (0.282, 0.444]  (0.111, 0.222]   (-inf, 2.522]   
25      (5.856, 7.111]   (0.282, 0.444]  (0.111, 0.222]   (-inf, 2.522]   
26      (7.111, 8.367]   (0.282, 0.444]  (0.222, 0.333]   (-inf, 2.522]   
27      (7.111, 8.367]   (0.282, 0.444]  (0.111, 0.222]   (-inf, 2.522]   
28      (5.856, 7.111]   (0.607, 0.769]   (-inf, 0.111]   (-inf, 2.522]   
29      (7.111, 8.367]   (0.607, 0.769]   (-inf, 0.111]   (-inf, 2.522]   
...                ...              ...             ...             ...   
1569    (5.856, 7.111]   (0.444, 0.607]  (0.111, 0.222]   (-inf, 2.522]   
1570    (5.856, 7.111]   (0.282, 0.444]  (0.444, 0.556]   (-inf, 2.522]   
1571    (5.856, 7.111]   (0.282, 0.444]  (0.111, 0.222]   (-inf, 2.522]   
1572    (7.111, 8.367]   (0.607, 0.769]  (0.222, 0.333]   (-inf, 2.522]   
1573    (5.856, 7.111]   (0.444, 0.607]  (0.111, 0.222]   (-inf, 2.522]   
1574     (-inf, 5.856]   (0.282, 0.444]  (0.778, 0.889]   (13.878, inf]   
1575    (7.111, 8.367]   (0.444, 0.607]  (0.333, 0.444]   (-inf, 2.522]   
1576    (7.111, 8.367]   (0.282, 0.444]  (0.556, 0.667]   (-inf, 2.522]   
1577    (5.856, 7.111]   (0.607, 0.769]  (0.111, 0.222]  (4.144, 5.767]   
1578    (5.856, 7.111]   (0.607, 0.769]  (0.111, 0.222]   (-inf, 2.522]   
1579    (5.856, 7.111]   (0.444, 0.607]   (-inf, 0.111]   (-inf, 2.522]   
1580    (7.111, 8.367]   (0.282, 0.444]  (0.222, 0.333]   (-inf, 2.522]   
1581    (5.856, 7.111]   (0.444, 0.607]   (-inf, 0.111]   (-inf, 2.522]   
1582    (5.856, 7.111]   (0.607, 0.769]   (-inf, 0.111]  (2.522, 4.144]   
1583    (5.856, 7.111]   (0.444, 0.607]  (0.222, 0.333]   (-inf, 2.522]   
1584    (5.856, 7.111]   (0.282, 0.444]  (0.333, 0.444]   (-inf, 2.522]   
1585    (7.111, 8.367]   (0.282, 0.444]  (0.333, 0.444]  (2.522, 4.144]   
1586    (7.111, 8.367]   (0.282, 0.444]  (0.333, 0.444]   (-inf, 2.522]   
1587     (-inf, 5.856]   (0.607, 0.769]   (-inf, 0.111]   (-inf, 2.522]   
1588    (7.111, 8.367]   (0.607, 0.769]  (0.222, 0.333]   (-inf, 2.522]   
1589    (5.856, 7.111]   (0.607, 0.769]  (0.111, 0.222]  (7.389, 9.011]   
1590    (5.856, 7.111]   (0.444, 0

### 4. Equal width discretization using Orange

In [63]:
#veh = Orange.data.Table("c://PW-PR//vehicle.tab")
wine=Orange.data.Table("https://academic.uprm.edu/eacuna/winequality-red.tab")
disc = Orange.preprocess.Discretize()
disc.method = Orange.preprocess.discretize.EqualWidth(n=10)
wine_disc = disc(wine)
print("Original dataset:")
for e in wine[:3]:
    print(e)

print("Discretized dataset:")
for e in wine_disc[:3]:
    print(e)

Original dataset:
[7.4, 0.700, 0.00, 1.90, 0.076, 11.0, 34.0, 0.99780, 3.51, 0.56, 9.40000000000000 | 5]
[7.8, 0.880, 0.00, 2.60, 0.098, 25.0, 67.0, 0.99680, 3.20, 0.68, 9.80000000000000 | 5]
[7.8, 0.760, 0.04, 2.30, 0.092, 15.0, 54.0, 0.99700, 3.26, 0.65, 9.80000000000000 | 5]
Discretized dataset:
[6.9 - 8, 0.558 - 0.704, < 0.1, < 2.36, 0.072 - 0.132, 8.1 - 15.2, < 34.3, 0.99688 - 0.99824, 3.5 - 3.63, 0.5 - 0.66, 9.05 - 9.7 | 5]
[6.9 - 8, 0.85 - 0.996, < 0.1, 2.36 - 3.82, 0.072 - 0.132, 22.3 - 29.4, 62.6 - 90.9, 0.99552 - 0.99688, 3.12 - 3.25, 0.66 - 0.83, 9.7 - 10.35 | 5]
[6.9 - 8, 0.704 - 0.85, < 0.1, < 2.36, 0.072 - 0.132, 8.1 - 15.2, 34.3 - 62.6, 0.99688 - 0.99824, 3.25 - 3.38, 0.5 - 0.66, 9.7 - 10.35 | 5]


### 5. Equal Frequency Discretization using Pandas

In [64]:
wine_data['pH_ex1'] = pd.qcut(wine_data['pH'], q=4,precision=0)
wine_data['pH_ex1'].value_counts()

(2.6, 3.2]    424
(3.2, 3.3]    398
(3.3, 3.4]    390
(3.4, 4.0]    387
Name: pH_ex1, dtype: int64

In [65]:
dfdisc1= dfa.apply(lambda x: pd.qcut(x,4,precision=2), axis=0)
dfdisc1.head()

fixed acidity volatile acidity    citric acid residual sugar      chlorides  \
0    (7.1, 7.9]     (0.64, 1.58]  (-0.01, 0.09]    (0.89, 1.9]  (0.07, 0.079]   
1    (7.1, 7.9]     (0.64, 1.58]  (-0.01, 0.09]     (2.2, 2.6]   (0.09, 0.61]   
2    (7.1, 7.9]     (0.64, 1.58]  (-0.01, 0.09]     (2.2, 2.6]   (0.09, 0.61]   
3   (9.2, 15.9]     (0.11, 0.39]    (0.42, 1.0]    (0.89, 1.9]  (0.07, 0.079]   
4    (7.1, 7.9]     (0.64, 1.58]  (-0.01, 0.09]    (0.89, 1.9]  (0.07, 0.079]   

  free sulfur dioxide total sulfur dioxide         density  \
0         (7.0, 14.0]         (22.0, 38.0]  (0.997, 0.998]   
1        (21.0, 72.0]        (62.0, 289.0]  (0.997, 0.998]   
2        (14.0, 21.0]         (38.0, 62.0]  (0.997, 0.998]   
3        (14.0, 21.0]         (38.0, 62.0]  (0.998, 1.004]   
4         (7.0, 14.0]         (22.0, 38.0]  (0.997, 0.998]   

                           pH     sulphates      alcohol  
0                 (3.4, 4.01]  (0.55, 0.62]  (8.39, 9.5]  
1  (2.7300000000000004, 3.21]  (0.62, 0.73]  (9.5, 10.2]  
2                (3.21, 3.31]  (0.62, 0.73]  (9.5, 10.2]  
3  (2.7300000000000004, 3.21]  (0.55, 0.62]  (9.5, 10.2]  
4                 (3.4, 4.01]  (0.55, 0.62]  (8.39, 9.5]

###  6. Equal Frequency Discretization using scikit-learn

In [66]:
est = KBinsDiscretizer(n_bins=10, encode='ordinal', strategy='quantile')
est.fit(dfa)  
Xt = est.transform(dfa)
Xt  

array([[3., 8., 0., ..., 9., 2., 1.],
       [4., 9., 0., ..., 2., 6., 3.],
       [4., 9., 1., ..., 3., 6., 3.],
       ...,
       [0., 4., 3., ..., 7., 7., 7.],
       [0., 7., 2., ..., 9., 7., 5.],
       [0., 1., 8., ..., 7., 6., 7.]])

In [67]:
#Converting the array into dataframe
tempodf=pd.DataFrame(Xt)
tempodf.columns=dfa.columns
tempodf.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1599.000000       1599.000000  1599.000000     1599.000000   
mean        4.615385          4.574109     4.555972        4.722326   
std         2.848980          2.882445     2.867838        2.829170   
min         0.000000          0.000000     0.000000        0.000000   
25%         2.000000          2.000000     2.000000        2.000000   
50%         5.000000          5.000000     5.000000        5.000000   
75%         7.000000          7.000000     7.000000        7.000000   
max         9.000000          9.000000     9.000000        9.000000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1599.000000          1599.000000           1599.000000  1599.000000   
mean      4.621639             4.707317              4.561601     4.517824   
std       2.859682             2.750927              2.837669     2.872253   
min       0.000000             0.000000              0.000000     0.000000   
25%       2.000000             2.000000              2.000000     2.000000   
50%       5.000000             5.000000              5.000000     5.000000   
75%       7.000000             7.000000              7.000000     7.000000   
max       9.000000             9.000000              9.000000     9.000000   

                pH    sulphates      alcohol  
count  1599.000000  1599.000000  1599.000000  
mean      4.586617     4.609131     4.629769  
std       2.860082     2.876984     2.856697  
min       0.000000     0.000000     0.000000  
25%       2.000000     2.000000     2.000000  
50%       5.000000     5.000000     5.000000  
75%       7.000000     7.000000     7.000000  
max       9.000000     9.000000     9.000000

### 7. Equal frequency Discretization using Orange 

In [68]:
disc = Orange.preprocess.Discretize()
disc.method = Orange.preprocess.discretize.EqualFreq(n=10)
wine1_disc = disc(wine)
print("Original dataset:")
for e in wine[:3]:
    print(e)

print("Discretized dataset:")
for e in wine1_disc[:3]:
    print(e)


Original dataset:
[7.4, 0.700, 0.00, 1.90, 0.076, 11.0, 34.0, 0.99780, 3.51, 0.56, 9.40000000000000 | 5]
[7.8, 0.880, 0.00, 2.60, 0.098, 25.0, 67.0, 0.99680, 3.20, 0.68, 9.80000000000000 | 5]
[7.8, 0.760, 0.04, 2.30, 0.092, 15.0, 54.0, 0.99700, 3.26, 0.65, 9.80000000000000 | 5]
Discretized dataset:
[7.2 - 7.5, 0.657 - 0.738, < 0.01, 1.85 - 1.95, 0.075 - 0.079, 10.5 - 13.5, 28.5 - 36.5, 0.99759 - 0.99816, 3.42 - 3.51, 0.54 - 0.56, 9.275 - 9.45 | 5]
[7.5 - 7.8, ≥ 0.738, < 0.01, 2.45 - 2.67, 0.093 - 0.106, 24.5 - 30.5, 54.5 - 68.5, 0.99676 - 0.99717, 3.19 - 3.24, 0.66 - 0.7, 9.58333333333334 - 9.85 | 5]
[7.5 - 7.8, ≥ 0.738, 0.01 - 0.07, 2.27 - 2.45, 0.086 - 0.093, 13.5 - 16.5, 44.5 - 54.5, 0.99676 - 0.99717, 3.24 - 3.27, 0.62 - 0.66, 9.58333333333334 - 9.85 | 5]


### 8. MDLP-Entropy Discretization using Orange

In [69]:
disc = Orange.preprocess.Discretize()
disc.method = Orange.preprocess.EntropyMDL(force=False)
wine1_disc = disc(wine)
print("Original dataset:")
for e in wine[:3]:
    print(e)

print("Discretized dataset:")
for e in wine1_disc[:3]:
    print(e)
    

Original dataset:
[7.4, 0.700, 0.00, 1.90, 0.076, 11.0, 34.0, 0.99780, 3.51, 0.56, 9.40000000000000 | 5]
[7.8, 0.880, 0.00, 2.60, 0.098, 25.0, 67.0, 0.99680, 3.20, 0.68, 9.80000000000000 | 5]
[7.8, 0.760, 0.04, 2.30, 0.092, 15.0, 54.0, 0.99700, 3.26, 0.65, 9.80000000000000 | 5]
Discretized dataset:
[< 10, 0.425 - 0.867, < 0.3, ≥ 0.068, < 56.5, ≥ 0.99537, 0.54 - 0.64, < 9.85 | 5]
[< 10, ≥ 0.867, < 0.3, ≥ 0.068, 56.5 - 95.5, ≥ 0.99537, ≥ 0.64, < 9.85 | 5]
[< 10, 0.425 - 0.867, < 0.3, ≥ 0.068, < 56.5, ≥ 0.99537, ≥ 0.64, < 9.85 | 5]
